import { Metadata } from "next";

const pluginNames: Record<string, string> = {
  patent: "Patent Analysis",
  pubmed: "PubMed Literature",
  staffing: "Hospital Staffing",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ pluginId: string }>;
}): Promise<Metadata> {
  const { pluginId } = await params;
  const pluginName = pluginNames[pluginId] || pluginId;

  return {
    title: `${pluginName} Reports - Report Hub`,
    description: `View and download ${pluginName} reports generated by AI`,
  };
}

export default function PluginReportsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
