import { Metadata } from "next";

const pluginNames: Record<string, string> = {
  patent: "Patent Analysis",
  pubmed: "PubMed Literature",
  staffing: "Hospital Staffing",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ pluginId: string }>;
}): Promise<Metadata> {
  const { pluginId } = await params;
  const pluginName = pluginNames[pluginId] || pluginId;

  return {
    title: `${pluginName} Report - Report Hub`,
    description: `View and download the ${pluginName} report generated by AI`,
  };
}

export default function ReportLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
